### ISSUE TITLE
failed to compile with v3.0.0 and the lastest commit

### ISSUE THREAD

**Issue by shenwei356** [jermp/sshash#32]
I'm trying to install the flugor, but it seems like sshash, as a dependency, is failed to compile.

Environments:

```
$ uname -a
Linux mBio 6.1.55-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Sep 23 12:13:56 UTC 2023 x86_64 GNU/Linux

$ gcc --version
gcc (GCC) 13.2.1 20230801

zlib: 1.3
```

```
$ cmake ..
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: Release
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/shenwei/Downloads/fulgor/sshash/build

$ make
[  3%] Building CXX object CMakeFiles/sshash_static.dir/include/gz/zip_stream.cpp.o
In file included from /home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:1:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:121:5: error: ‘uint32_t’ does not name a type
  121 |     uint32_t get_crc() const;
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:67:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   66 | #include <vector>
  +++ |+#include <cstdint>
   67 | 
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:124:5: error: ‘uint32_t’ does not name a type
  124 |     uint32_t get_in_size() const;
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:124:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:137:5: error: ‘uint32_t’ does not name a type
  137 |     uint32_t crc_;
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:137:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:180:5: error: ‘uint32_t’ does not name a type
  180 |     uint32_t get_crc() const;
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:180:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:186:5: error: ‘uint32_t’ does not name a type
  186 |     uint32_t get_in_size() const;
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:186:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:200:5: error: ‘uint32_t’ does not name a type
  200 |     uint32_t crc_;
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:200:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:285:5: error: ‘uint32_t’ does not name a type
  285 |     uint32_t gzip_crc_;
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:285:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:286:5: error: ‘uint32_t’ does not name a type
  286 |     uint32_t gzip_data_size_;
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.hpp:286:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In constructor ‘basic_zip_streambuf<CharT, Traits>::basic_zip_streambuf(ostream_reference, int, ZipStrategy, int, int, size_t)’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:37:83: error: class ‘basic_zip_streambuf<CharT, Traits>’ does not have any field named ‘crc_’
   37 |     : ostream_(ostream), output_buffer_(buffer_size, 0), buffer_(buffer_size, 0), crc_(0) {
      |                                                                                   ^~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘std::streamsize basic_zip_streambuf<CharT, Traits>::flush()’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:101:5: error: ‘crc_’ was not declared in this scope
  101 |     crc_ = static_cast<uint32_t>(crc32(crc_, zip_stream_.next_in, zip_stream_.avail_in));
      |     ^~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:101:24: error: ‘uint32_t’ does not name a type
  101 |     crc_ = static_cast<uint32_t>(crc32(crc_, zip_stream_.next_in, zip_stream_.avail_in));
      |                        ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:5:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
    4 | #include <cstring>
  +++ |+#include <cstdint>
    5 | 
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: At global scope:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:136:1: error: ‘uint32_t’ does not name a type
  136 | uint32_t basic_zip_streambuf<CharT, Traits>::get_crc() const {
      | ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:136:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:141:1: error: ‘uint32_t’ does not name a type
  141 | uint32_t basic_zip_streambuf<CharT, Traits>::get_in_size() const {
      | ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:141:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘bool basic_zip_streambuf<CharT, Traits>::zip_to_stream(char*, std::streamsize)’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:163:5: error: ‘crc_’ was not declared in this scope
  163 |     crc_ = static_cast<uint32_t>(crc32(crc_, zip_stream_.next_in, zip_stream_.avail_in));
      |     ^~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:163:24: error: ‘uint32_t’ does not name a type
  163 |     crc_ = static_cast<uint32_t>(crc32(crc_, zip_stream_.next_in, zip_stream_.avail_in));
      |                        ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:163:24: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In constructor ‘basic_unzip_streambuf<CharT, Traits>::basic_unzip_streambuf(istream_reference, int, size_t, size_t)’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:193:87: error: class ‘basic_unzip_streambuf<CharT, Traits>’ does not have any field named ‘crc_’
  193 |     : istream_(istream), input_buffer_(input_buffer_size), buffer_(read_buffer_size), crc_(0) {
      |                                                                                       ^~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: At global scope:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:259:1: error: ‘uint32_t’ does not name a type
  259 | uint32_t basic_unzip_streambuf<CharT, Traits>::get_crc() const {
      | ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:259:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:269:1: error: ‘uint32_t’ does not name a type
  269 | uint32_t basic_unzip_streambuf<CharT, Traits>::get_in_size() const {
      | ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:269:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘std::streamsize basic_unzip_streambuf<CharT, Traits>::unzip_from_stream(char_type*, std::streamsize)’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:304:5: error: ‘crc_’ was not declared in this scope
  304 |     crc_ = static_cast<uint32_t>(crc32(crc_, reinterpret_cast<byte_type*>(buffer), (uInt)theSize));
      |     ^~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:304:24: error: ‘uint32_t’ does not name a type
  304 |     crc_ = static_cast<uint32_t>(crc32(crc_, reinterpret_cast<byte_type*>(buffer), (uInt)theSize));
      |                        ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:304:24: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘basic_zip_ostream<CharT, Traits>& basic_zip_ostream<CharT, Traits>::add_footer()’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:391:5: error: ‘uint32_t’ was not declared in this scope
  391 |     uint32_t crc = this->get_crc();
      |     ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:391:5: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:393:51: error: ‘crc’ was not declared in this scope; did you mean ‘crc32’?
  393 |         this->get_ostream().put(static_cast<char>(crc & 0xff));
      |                                                   ^~~
      |                                                   crc32
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:397:13: error: expected ‘;’ before ‘length’
  397 |     uint32_t length = this->get_in_size();
      |             ^~~~~~~
      |             ;
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:399:51: error: ‘length’ was not declared in this scope
  399 |         this->get_ostream().put(static_cast<char>(length & 0xff));
      |                                                   ^~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In constructor ‘basic_zip_istream<CharT, Traits>::basic_zip_istream(istream_reference, int, size_t, size_t)’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:417:7: error: class ‘basic_zip_istream<CharT, Traits>’ does not have any field named ‘gzip_crc_’
  417 |     , gzip_crc_(0)
      |       ^~~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:418:7: error: class ‘basic_zip_istream<CharT, Traits>’ does not have any field named ‘gzip_data_size_’
  418 |     , gzip_data_size_(0) {
      |       ^~~~~~~~~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘bool basic_zip_istream<CharT, Traits>::check_crc()’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:434:31: error: ‘gzip_crc_’ was not declared in this scope
  434 |     return this->get_crc() == gzip_crc_;
      |                               ^~~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘bool basic_zip_istream<CharT, Traits>::check_data_size() const’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:439:36: error: ‘gzip_data_size_’ was not declared in this scope; did you mean ‘get_gzip_data_size’?
  439 |     return this->get_out_size() == gzip_data_size_;
      |                                    ^~~~~~~~~~~~~~~
      |                                    get_gzip_data_size
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘long int basic_zip_istream<CharT, Traits>::get_gzip_crc() const’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:444:12: error: ‘gzip_crc_’ was not declared in this scope
  444 |     return gzip_crc_;
      |            ^~~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘long int basic_zip_istream<CharT, Traits>::get_gzip_data_size() const’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:449:12: error: ‘gzip_data_size_’ was not declared in this scope; did you mean ‘get_gzip_data_size’?
  449 |     return gzip_data_size_;
      |            ^~~~~~~~~~~~~~~
      |            get_gzip_data_size
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In member function ‘void basic_zip_istream<CharT, Traits>::read_footer()’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:511:9: error: ‘gzip_crc_’ was not declared in this scope
  511 |         gzip_crc_ = 0;
      |         ^~~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:513:39: error: ‘uint32_t’ does not name a type
  513 |             gzip_crc_ += (static_cast<uint32_t>(this->get_istream().get()) & 0xff) << (8 * n);
      |                                       ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:513:39: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:515:9: error: ‘gzip_data_size_’ was not declared in this scope; did you mean ‘get_gzip_data_size’?
  515 |         gzip_data_size_ = 0;
      |         ^~~~~~~~~~~~~~~
      |         get_gzip_data_size
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:517:45: error: ‘uint32_t’ does not name a type
  517 |             gzip_data_size_ += (static_cast<uint32_t>(this->get_istream().get()) & 0xff) << (8 * n);
      |                                             ^~~~~~~~
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:517:45: note: ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp: In instantiation of ‘bool basic_zip_istream<CharT, Traits>::check_crc() [with CharT = char; Traits = std::char_traits<char>]’:
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:527:16:   required from here
/home/shenwei/Downloads/fulgor/sshash/include/gz/zip_stream.cpp:434:18: error: ‘class basic_zip_istream<char>’ has no member named ‘get_crc’
  434 |     return this->get_crc() == gzip_crc_;
      |            ~~~~~~^~~~~~~
make[2]: *** [CMakeFiles/sshash_static.dir/build.make:76: CMakeFiles/sshash_static.dir/include/gz/zip_stream.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/sshash_static.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by jermp** [comment]
Hi @shenwei356,
mmh that's curious but I do not think is a SSHash problem. It seems C++ needs to be told what a `uint32_t` is.

In fact, these lines in your cmake output look suspicious to me:

    -- Check for working C compiler: /usr/bin/cc - skipped
    ...
    -- Check for working CXX compiler: /usr/bin/c++ - skipped

Have you tried to specify the C++ compiler during the creation of the makefile?
Something like this: `cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc-11 -DCMAKE_CXX_COMPILER=/usr/bin/g++-11`.

Let me know.

-Giulio

**Comment by shenwei356** [comment]
Hmm, I don't have the gcc-11 or g++-11, and I failed to install gcc12. The command below still failed.

```
cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++
```

And in a server, it compiles smoothly, though there's still a `Check for working C compiler: /usr/bin/cc - skipped`.

```
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE: Release
-- Compiling for processor: x86_64
-- Compiling with flags: -march=native -mbmi2 -msse4.2
-- Compiling with flags: -std=c++17 -O3 -ggdb -pthread -Wall -Wextra -Wno-missing-braces -Wno-unknown-attributes -Wno-unused-function
-- Configuring done
-- Generating done
-- Build files have been written to: /homes/shenwei/download/sshash/build
```

**Comment by jermp** [comment]
Ok so it works on another server. What's the version of GCC for which it does not compile?
And the one for which it does?

**Comment by shenwei356** [comment]
GCC 8.5.0 worked, and 13.2.1 did not.

**Comment by jermp** [comment]
I have to update my LTS to test with gcc12 and gcc13, which are only available for Ubuntu 22.04.
Under g++11 it works.

In the meanwhile, you can try to include the header `cstdint` to see if it solves the problem for the new compiler; see here: https://stackoverflow.com/questions/11069108/uint32-t-does-not-name-a-type.

**Comment by shenwei356** [comment]
It worked by adding there lines (maybe only one of them is needed)

```
#include <stdint.h>
#include <cstdint>
#include <sys/types.h>
```

to three files:

```
external/sshash/include/gz/zip_stream.hpp
external/ggcat/crates/capi/ggcat-cpp-api/src/ggcat.cc
external/ggcat/crates/capi/ggcat-cpp-api/include/ggcat.hh
```

Thanks, Giulio!

**Comment by jermp** [comment]
It complies just fine with gcc 12.3.0.
